# Generated by Django 5.1.6 on 2026-03-14 15:35

import tournaments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='invite_code',
            field=models.CharField(default=tournaments.models.generate_invite_code, max_length=8, unique=True),
        ),
    ]
